apiVersion: apps/v1
kind: Deployment

metadata:
  name: cricket-pipeline
  namespace: cricket

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cricket-pipeline

  template:

    metadata:
      labels:
        app: cricket-pipeline

    spec:
      containers:

      - name: cricket-pipeline

        image: kmohanr72/cricket-pipeline:v1

        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: cricket-config

        - secretRef:
            name: cricket-secret
